############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "A propos"
url = "/about"
weight = 2


[[main]]
weight = 4
name = "Blog"
url = "/blog"


# footer menu
[[footer]]
name = "A propos"
url = "/about"
weight = 1


